## Тренажер

In [1]:
import numpy as np
import scipy.stats as st
import pandas as pd
import math
import matplotlib.pyplot as plt

### Задание_1

Определите размер необходимой выборки для исследования среднего чека за кофе в городе N, если известны следующие параметры:
- погрешность (Δ);
- дисперсия (σ2);
- уровень доверия (1-α).

Ответ округлите до целого.

Внимание: не удаляйте код ниже, а дополните его. Функция нужна для проверки вашего решения.

#### Поиск критического значения Z

In [3]:
delta = 5
sigsqr = 225
conf = 0.95

In [6]:
# левосторонний тест
z = st.norm.ppf(1 - conf)
z

-1.6448536269514722

In [8]:
# правосторонний тест
z = st.norm.ppf(conf)
z

1.6448536269514722

In [10]:
# двусторонний тест
z = st.norm.ppf(1 - (1 - conf) / 2)
z

1.959963984540054

In [21]:
def sample(delta, sigsqr, conf):
    z = st.norm.ppf(1 - (1 - conf) / 2)
    n = sigsqr * (z / delta) ** 2
    return int(np.ceil(n))

In [22]:
sample(delta, sigsqr, conf)

35

In [45]:
def sample(delta, sigsqr, conf):
    z = st.norm.ppf((1 + conf) / 2)
    n = sigsqr * z ** 2 / delta ** 2
    return round(np.ceil(n))

In [46]:
sample(delta, sigsqr, conf)

35

### Задание_2
Постройте доверительный интервал для среднего значения, если известны:
- объём выборки (n) от 10 до 26;
- среднее значение по выборке (x¯);
- стандартное отклонение (σ).

В ответе укажите длину полученного доверительного интервала - разницу между правым и левым концом, - округлённую до целого.

Подсказка: при малом размере выборки предпочтительнее использовать t-распределение из модуля scipy.

In [54]:
def interval(n, mean, sig, conf):
    ci_lower, ci_upper = st.t.interval(
        confidence = conf,
        df = n - 1,
        loc = mean,
        scale = sig / np.sqrt(n)       
    )
    return round(ci_upper - ci_lower)

In [55]:
interval(26, 54.3, 9.2, 0.95)

7

In [59]:
def interval(n, mean, sig, conf):
    h = st.t.interval(
        confidence = conf,
        df = n - 1,
        loc = mean,
        scale = sig / np.sqrt(n)       
    )
    print(h)
    return round(h[1] - h[0])

In [60]:
interval(26, 54.3, 9.2, 0.95)

(50.5840395815666, 58.015960418433394)


7

### Задание_3
Постройте доверительный интервал для среднего значения, если известны:
- объём выборки (n) от 30 до 50;
- среднее значение по выборке (x¯);
- стандартное отклонение (σ).

В ответе укажите длину полученного доверительного интервала — разницу между правым и левым концом, — округлённую до целого.

Подсказка: при малом размере выборки предпочтительнее использовать t-распределение из модуля scipy.

In [63]:
def interval(n, mean, sig, conf):
    h = st.norm.interval(
        confidence = conf,
        loc = mean,
        scale = sig / np.sqrt(n)
    )
    print(h)
    return round(h[1] - h[0])

In [64]:
interval(45, 13.2, 3.5, 0.99)

(11.856063135060033, 14.543936864939965)


3

### Задание_4
Профессор университета читал онлайн-лекции вместо очных занятий из-за Covid-19. Позже он загружал в облако записанные лекции для студентов, которые просматривали их в записи. Профессор считает, что учащиеся, которые посещают занятия в учебное время и участвуют в процессе, более успешны. Поэтому он записал средние оценки студентов в конце семестра, чтобы проверить эту гипотезу.

С помощью статистического теста проверьте, является ли мнение профессора статистически значимым, используя уровень значимости 0,05 для оценки нулевой и альтернативной гипотез.

В рамках задания считается, что данные распределены нормально, а вариация в группах одинаковая.

In [70]:
sync = np.round(81 + 6 * np.random.standard_normal(22),1)
asyncr = np.round(74 + 6 * np.random.standard_normal(14),1)

In [71]:
print(sync)

[76.5 69.9 80.6 80.3 86.6 79.1 80.2 78.2 80.6 73.9 86.9 77.6 82.7 83.2
 84.2 81.6 85.  91.7 79.5 94.1 75.4 83.7]


In [72]:
print(asyncr)

[71.7 88.8 66.9 79.6 66.7 71.8 75.3 67.3 71.6 77.8 72.  70.5 75.8 76.6]


In [74]:
# H0 - выборки не имеют стат. значимых различий
# H1 - выборки имеют стат. значимые различия

significance = 0.05
stat, p = st.ttest_ind(sync, asyncr)
if p < significance:
    print('Отклоняем нулевую гипотезу')
else:
    print('Не отклоняем нулевую гипотезу')

Отклоняем нулевую гипотезу


### Задание_5
Центр здоровья университета диагностировал у восемнадцати студентов высокий уровень холестерина в предыдущем семестре. Медицинский персонал рассказал этим пациентам об опасности высокого уровня холестерина и прописал диету. Через месяц больные пришли на контроль, и у них повторно проверили уровень холестерина. Проверьте, есть ли разница в уровнях холестерина у пациентов.

В соответствии с этой информацией проведите проверку гипотезы, чтобы проверить, есть ли снижение уровня холестерина у пациентов после диеты, используя уровень значимости 0,05.

В рамках задания считается, что данные распределены нормально, а вариация в группах одинаковая.

In [75]:
before_diet = np.round(239 + 15 * np.random.standard_normal(18),0)
after_diet = np.round(206 + 15 * np.random.standard_normal(18),0)

In [76]:
before_diet

array([244., 246., 243., 209., 207., 252., 252., 235., 210., 273., 250.,
       225., 245., 235., 258., 254., 250., 252.])

In [77]:
after_diet

array([204., 218., 209., 205., 195., 230., 187., 214., 200., 193., 205.,
       222., 186., 176., 203., 232., 204., 195.])

In [78]:
# H0 - выборки не имеют стат. значимых различий
# H1 - выборки имеют стат. значимые различия

stat, p = st.ttest_rel(a = before_diet, b = after_diet)
if p < 0.05:
    print('Отклоняем нулевую гипотезу')
else:
    print('Не отклоняем нулевую гипотезу')

Отклоняем нулевую гипотезу


### Задание_6
Представьте, что вы хотите разоблачить “волшебника” который считает, что умеет предсказывать погоду на завтра, отвечая просто: дождь или солнце. Вы пронаблюдали за ответами “волшебника” в течении какого-то периода времени и получили некие результаты:

In [91]:
d1 = np.random.choice(range(8,18),(1,2))
d2 = np.random.choice(range(28,41),(1,2))
data = np.concatenate((d1, d2), axis=0)
observations = pd.DataFrame(data,
                            index=['Дождь','Солнце'],
                            columns=['Верные ответы волшебника','Неверные ответы'])
observations

Верные ответы волшебника  Неверные ответы
Дождь                         12               14
Солнце                        34               37

Можно ли сказать, что маг действительно умеет предсказывать погоду? Уровень значимости принимаем за 0.05.

In [92]:
oddsratio, p = st.fisher_exact(observations)
if p < 0.05:
    print('Отклоняем нулевую гипотезу. Есть некоторая зависимость')
else:
    print('Не отклоням нулевую гипотезу. Выборки, вероятно, независимы')

Не отклоням нулевую гипотезу. Выборки, вероятно, независимы
